#ifndef _KEYPAD_H
#define _KEYPAD_H


#define KEYPAD_ROW1_PORT_ID		PORT1_ID
#define KEYPAD_ROW1_PIN_ID		PIN0_ID

#define KEYPAD_ROW2_PORT_ID		PORT1_ID
#define KEYPAD_ROW2_PIN_ID		PIN1_ID

#define KEYPAD_ROW3_PORT_ID		PORT1_ID
#define KEYPAD_ROW3_PIN_ID		PIN2_ID

#define KEYPAD_ROW4_PORT_ID		PORT1_ID
#define KEYPAD_ROW4_PIN_ID		PIN3_ID

#define KEYPAD_COL1_PORT_ID		PORT1_ID
#define KEYPAD_COL1_PIN_ID		PIN4_ID

#define KEYPAD_COL2_PORT_ID		PORT1_ID
#define KEYPAD_COL2_PIN_ID		PIN5_ID

#define KEYPAD_COL3_PORT_ID		PORT1_ID
#define KEYPAD_COL3_PIN_ID		PIN6_ID

#define KEYPAD_COL4_PORT_ID		PORT1_ID
#define KEYPAD_COL4_PIN_ID		PIN7_ID


unsigned char KEYPAD_returnPressedKey();

#endif